name: Build and Deploy React Native App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd ExpenseTracker
          npm install --legacy-peer-deps

      - name: Install Expo modules
        run: |
          cd ExpenseTracker
          npx expo install expo-modules-core expo-dev-client -- --legacy-peer-deps

      - name: Prebuild Expo project
        run: |
          cd ExpenseTracker
          npx expo prebuild

      - name: Install CocoaPods dependencies
        run: |
          cd ExpenseTracker/ios
          pod install

      - name: Decode and install certificates
        run: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > Certificate.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > Profile.mobileprovision
          security import Certificate.p12 -k ~/Library/Keychains/login.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp Profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build iOS
        run: |
          cd ExpenseTracker
          xcodebuild -workspace ios/ExpenseTracker.xcworkspace -scheme ExpenseTracker -sdk iphoneos -configuration Release archive -archivePath $GITHUB_WORKSPACE/build/ExpenseTracker.xcarchive

      - name: Export IPA
        run: |
          cd ExpenseTracker
          xcodebuild -exportArchive -archivePath $GITHUB_WORKSPACE/build/ExpenseTracker.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $GITHUB_WORKSPACE/build
