platform :ios, '10.0'

target 'ExpenseTracker' do
  # Pods for ExpenseTracker
  pod 'ExpoModulesCore', :path => '../node_modules/expo-modules-core'

  # Add new pods below this line
  use_expo_modules!
end
